spring:
  application:
    name: EurekaServer
    # 设置eureka的访问账号密码
#  security:
#    user:
#      name: malixi
#      password: malixi
eureka:
  server:
    enable-self-preservation: false # 关闭自我保护机制
    #此配置建议只试用开发和测试环境
    #驱逐下线的服务，间隔,5秒，默认是60
    eviction-interval-timer-in-ms: 5000
  instance:
    hostname: 192.168.72.80
  client:
    #是否将自己注册到Eureka Server,默认为true，由于当前就是server，故而设置成false，表明该服务不会向eureka注册自己的信息
    register-with-eureka: true
    #是否从eureka server获取注册信息，由于单节点，不需要同步其他节点数据，用false
    fetch-registry: true
    #设置服务注册中心的URL，用于client和server端交流
    service-url:
      defaultZone: http://192.168.72.81:8000/eureka/
      #defaultZone: http://127.0.0.1:8000/eureka/
server:
  port: 7900


