spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启 从eureka里面拉取注册
      routes:
        - id: dso-one
          predicates:
            - Path=/dpOne/**    #配置断言 路径
          uri: lb://stn #配置 负载均衡 调取服务名为 stn
          filters:
            - StripPrefix=1  #省略path--dso-one
    nacos:
      server-addr: 192.168.3.86:8848
    sentinel:
      eager: true  # 模式
      transport:
        dashboard: 192.168.3.86:9999  # 对应的dashboard
  application:
    name: myGateWay

server:
  port: 8899


