spring:     # 配置不同的环境启动
  application:
    #name: service2 # 配置服务名称
    name: service # 配置服务名称 配置负载均衡

eureka:
  client:
    service-url:
      defaultZone: http://192.168.72.80:7900/eureka/ #z

      #defaultZone: http://malixi:malixi@192.168.72.80:7900/eureka/ #账号密码的连接方式
server:
  port: 82



