spring:
  boot:
    admin:
      client:
        url: http://192.168.72.80:8888
  application:
    name: EurekaServer
eureka:
  server:
    enable-self-preservation: false # 关闭自我保护机制
    #此配置建议只试用开发和测试环境
    #驱逐下线的服务，间隔,5秒，默认是60
    eviction-interval-timer-in-ms: 30000
  instance:
    hostname: 192.168.72.81 #hostname 用来查找主机的    appname 标识分组的
              #euk2.com
  client:
    #是否将自己注册到Eureka Server,默认为true，由于当前就是server，故而设置成false，表明该服务不会向eureka注册自己的信息
    register-with-eureka: true
    #是否从eureka server获取注册信息，由于单节点，不需要同步其他节点数据，用false
    fetch-registry: true
    #设置服务注册中心的URL，用于client和server端交流
    service-url:
      defaultZone: http://192.168.72.80:7900/eureka/
      #defaultZone: http://euk1.com:7900/eureka/
      #defaultZone: http://127.0.0.1:7900/eureka/
server:
  port: 8000
  
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: always